# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: E:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/iF_ARM.bd
# Block Designs: The module: 'iF_ARM' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_Adder_0_0/iF_ARM_Adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_Adder_0_0 || ORIG_REF_NAME==iF_ARM_Adder_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_MUX2to1_0_0/iF_ARM_MUX2to1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_MUX2to1_0_0 || ORIG_REF_NAME==iF_ARM_MUX2to1_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_REG_0_0/iF_ARM_REG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_REG_0_0 || ORIG_REF_NAME==iF_ARM_REG_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_xlconstant_0_0/iF_ARM_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_xlconstant_0_0 || ORIG_REF_NAME==iF_ARM_xlconstant_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_blk_mem_gen_2_1/iF_ARM_blk_mem_gen_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_blk_mem_gen_2_1 || ORIG_REF_NAME==iF_ARM_blk_mem_gen_2_1} -quiet] -quiet

# XDC: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_blk_mem_gen_2_1/iF_ARM_blk_mem_gen_2_1_ooc.xdc

# XDC: E:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/iF_ARM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iF_ARM'. Do not add the DONT_TOUCH constraint.

# Block Designs: E:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/iF_ARM.bd
# Block Designs: The module: 'iF_ARM' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_Adder_0_0/iF_ARM_Adder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_Adder_0_0 || ORIG_REF_NAME==iF_ARM_Adder_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_MUX2to1_0_0/iF_ARM_MUX2to1_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_MUX2to1_0_0 || ORIG_REF_NAME==iF_ARM_MUX2to1_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_REG_0_0/iF_ARM_REG_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_REG_0_0 || ORIG_REF_NAME==iF_ARM_REG_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_xlconstant_0_0/iF_ARM_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_xlconstant_0_0 || ORIG_REF_NAME==iF_ARM_xlconstant_0_0} -quiet] -quiet

# IP: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_blk_mem_gen_2_1/iF_ARM_blk_mem_gen_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iF_ARM_blk_mem_gen_2_1 || ORIG_REF_NAME==iF_ARM_blk_mem_gen_2_1} -quiet] -quiet

# XDC: e:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/ip/iF_ARM_blk_mem_gen_2_1/iF_ARM_blk_mem_gen_2_1_ooc.xdc

# XDC: E:/ARM/ARM/ARM.srcs/sources_1/bd/iF_ARM/iF_ARM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iF_ARM'. Do not add the DONT_TOUCH constraint.
